version: "3.8"

services:
  api:
      build:
            context: .
            dockerfile: Dockerfile
      ports:
          - "8080:8080" 
      volumes:
        - ./logs:/app/logs
      depends_on:
            postgres:
             condition: service_healthy
      environment:
      - LOG_PATH=/app/logs/app.log       
  postgres:
      image: postgres:15
      environment:
            POSTGRES_USER: user    
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: postgres
      ports:
            - "5432:5432"
      volumes:
         - postgres_data:/var/lib/postgresql/data    
      healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
            interval: 5s
            timeout: 5s
            retries: 10
volumes:
    postgres_data:
    
